### ISSUE TITLE
profile lock has a conflict

### ISSUE THREAD

**Issue by EricADockery** [sclampet/i-have-more-money-than#10]
[!] ERROR: Parsing unable to continue due to merge conflicts present in:
the file located at /Users/p2807240/Downloads/TakeHomeTest/i-have-more-money-than-master/I Have More Money Than/Podfile.lock
PODS:
  - SVProgressHUD (2.2.5)

DEPENDENCIES:
  - SVProgressHUD

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - SVProgressHUD

SPEC CHECKSUMS:
  SVProgressHUD: 1428aafac632c1f86f62aa4243ec12008d7a51d6

<<<<<<< HEAD
PODFILE CHECKSUM: 5ba34f4841c94ccb6fc8bb004decf28fb954735b
=======
PODFILE CHECKSUM: 1026a8ce452fc241243ba630344662fee193e922
>>>>>>> parent of 8a8c044... add initial ui test file

COCOAPODS: 1.7.5

**Comment by sclampet** [comment]
Fixed and updated. Sorry about for the inconvenience.
