### ISSUE TITLE
UI tests won't build after resolving pod lock issue

### ISSUE THREAD

**Issue by EricADockery** [sclampet/i-have-more-money-than#11]
[!] Unable to find a target named `I Have More Money ThanUITests`, did find `I Have More Money Than` and `I Have More Money ThanTests`.

**Comment by sclampet** [comment]
This is is strange that it's looking for UITests when I did not write any. I updated my project and this shouldn't be an issue anymore. I apologize for the inconvenience @EricADockery .  You should be able to re-clone and run the app.
